### ISSUE TITLE
Decouple Label Transforms

### ISSUE THREAD

**Issue by jeff-hernandez** [FeatureLabs/compose#112]
It would be helpful to use label transforms without requiring cutoff times or an entity id. Some transforms like `apply_lead` should still require cutoff times, but we want to decouple as much as possible.

**Comment by kmax12** [comment]
when do this the api shouldn't be repetative. for example, you currently have to do `LabelTimes(df["points"], name="points"`). We shouldn't have to give the name twice

**Comment by jeff-hernandez** [comment]
This was done in #135.
