### ISSUE TITLE
Add Context

### ISSUE THREAD

**Issue by jeff-hernandez** [FeatureLabs/compose#65]
User can add parameter in labeling function to access context.

```python
def labeling_function(df, context):
    context.window  # (start_time, stop_time)
    context.gap  # (start_time, stop_time)
    context.slice  # current slice
    ...
```

**Comment by jeff-hernandez** [comment]
As an alternative, what about creating a subclass of a pandas data frame?

```python
class DataSlice(pd.DataFrame):
    ...
```
```
def labeling_function(df):
    df.context.window
    df.context.gap
    df.context.slice
    ...
```

**Comment by kmax12** [comment]
I like the subclass approach. one thought is that we should only add one top level attribute. so it would be `df.context.window`, `df.context.gap`, etc
