### ISSUE TITLE
No way to balance labels per entity

### ISSUE THREAD

**Issue by wang19k** [FeatureLabs/compose#90]
If the labels are not very balanced and we want to limit the number of examples per entity, sometimes all of the same label are returned for an entity.

**Comment by jeff-hernandez** [comment]
Hi @wang19k,

The [sample transform](https://compose.featurelabs.com/en/latest/guides/using_label_transforms.html#Categorical-Labels) can balance out the number of examples per label.

```python
>>> examples_per_label = {'A': 10, 'B': 10, 'C': 10}
>>> labels.sample(n=examples_per_label)
```

Let me know if this helps.

**Comment by wang19k** [comment]
Hi @jeff-hernandez sample can balance the labels for all of the label times, but it seems not per entity?

**Comment by jeff-hernandez** [comment]
Ah, that makes sense. If I understand correctly, we want to sample specific labels per entity. For example, if we have labels times with customers as the target entity, then we'd be able to sample a specific number of labels per customer. Is this correct?

```python
{'customer_1': {'A': 2, 'B': 2, 'C': 2}, 'customer_2': {'A': 2, 'B': 2, 'C': 2}, ...}
```

**Comment by wang19k** [comment]
Yep that is the goal

**Comment by jeff-hernandez** [comment]
Thank you for clarifying. I will look into this and keep you updated.

**Comment by jeff-hernandez** [comment]
*API Proposals*

# Balance Labels per Entity

I have few ideas on how to resolve this issue. Any feedback is appreciated and helpful for deciding which approach to take.

## Examples

The following examples are based on two tasks and three approaches. For each task, we apply each approach to show what the API can look like. In the first task, we sample two random labels per entity. In the second task, we dynamically sample labels per entity.

### Approaches

1. #### Entity Iterations

    The label times has an entity property that returns an iterable. While iterating through each entity, the samples can be appended to create new label times.

    ##### Two Labels per Entity

    ```python
    samples = lt.head(0)
    for key, entity in lt.entity:
        sample = entity.sample(n=2)
        samples = samples.append(sample)
    ```

    ##### Dynamic Labels per Entity

    ```python
    samples = lt.head(0)

    for key, entity in lt.entity:
        if key == 'A':
            sample = entity.sample(n={True: 2, False: 2})
        elif key == 'C':
            sample = entity.sample(n={True: 4, False: 4})
        else:
            sample = entity.sample(n=3)
            
        samples = samples.append(sample)
    ```

2. #### Entity Method

    The label times has an entity method to return labels for a specific entity. The samples can be appended to create new label times.

    ##### Two Labels per Entity

    ```python
    samples = lt.head(0)
    samples = samples.append(lt.entity('A').sample(n=2))
    samples = samples.append(lt.entity('B').sample(n=2))
    samples = samples.append(lt.entity('C').sample(n=2))
    ```

    ##### Dynamic Labels per Entity

    ```python
    samples = lt.head(0)
    samples = samples.append(lt.entity('A').sample(n={True: 2, False: 2}))
    samples = samples.append(lt.entity('B').sample(n=3))
    samples = samples.append(lt.entity('C').sample(n={True: 4, False: 4}))
    ```

3. #### Sample Function

    The sample transform has an entity parameter that can apply a user defined sampling function per entity. 

    ##### Two Labels per Entity

    ```python
    def sample(entity):
        return  entity.sample(n=2)

    samples = lt.sample(entity=sample)
    ```

    ##### Dynamic Labels per Entity

    ```python
    def sample(entity):
        key = entity.columns.name
        if key == 'A':
            return entity.sample(n={True: 2, False: 2})
        elif key == 'C':
            return entity.sample(n={True: 4, False: 4})
        else:
            return entity.sample(n=3)

    samples = lt.sample(entity=sample)
    ```

**Comment by wang19k** [comment]
Hi @jeff-hernandez sorry I think I wasn't super clear. I think the main issue is that if we want to limit the number of examples per entity (for example when calling `search`) we may get a very unbalanced/unrepresentative label set if our data isn't balanced (like for example I'm running into an issue of getting all 0s when I set num_examples_per_instance=10 because it cuts off the data without ensuring that a representative label set is returned). With the sample method it seems I have to set num_examples_per_instance=-1, generate all of the labels, and then sample from there. Would there be anyway to make sure that a good representation is returned from the get go? Again apologies for not being more clear from the start.

**Comment by jeff-hernandez** [comment]
@wang19k Thank you for clarifying. That makes sense and is a great idea. If I understand correctly, we can balance the labels during the search. If so, maybe `num_examples_per_instance` can also be set to specify which labels?

```python
lt = lm.search(
    ...
    num_examples_per_instance={True: 2, False: 2},
)
```

Also, if an entity does not contain enough data to return the number of examples specified, what would be the expected outcome?

**Comment by jeff-hernandez** [comment]
Currently, the search will return up to the `num_examples_per_instance` parameter, because an entity may not contain enough data to create the next label. So, it continues to create labels on the next entity which can also result in unbalanced labels.

When an entity does not contain enough data to create labels, is there an expected outcome that would be more helpful?

**Comment by wang19k** [comment]
Hi Jeff, I think that having num_examples_per_instance as dictionary would be good. I'm assuming could also be keyed by multiple categorical/numerical variables (like {'A': 2, 'B':3, 'C': 3}). In terms of behavior, basically it would be useful if in the example above, the search would return max(2, # of 'A' labels) number of 'A' labels. The use cases would be the following:

- If the data had labels with exactly 2 'A's, 3 'B's, and 3 'C's, then this would be returned.
- If the data has 5 'A', 3 'B's, and 3 'C's, then all of the labels would be returned. I know this is a little difference to how `num_examples_per_instance` currently behaves, so if there could potentially be a way to specify = vs >= (min) that could potentially be useful. 
- If the data had 1 'A', 3 'B's, and 3 'C's, then all of the labels would be returned.

It seems that if the labels are calculated anyways it would be easier to generate them this way and then afterwards remove them by processing if necessary. Let me know what you think and thanks again!

**Comment by jeff-hernandez** [comment]
Yes, the dictionary could also be keyed by multiple categorical/numerical variables. I think the assumption here is that the labeling function will return labels as defined in the dictionary. Otherwise, we'd either need to raise an error or ignore the label?

**Comment by jeff-hernandez** [comment]
In regards to the behavior, suppose a user searches for labels with this `num_examples_per_instance`:

```python
lm.search(
    df,
    num_examples_per_instance={
    'A': 2,
    'B': 3,
    'C': 3,
    },
    ...
)
```

If an entity in this data frame only contains enough data to create one `A` (not two `A's` as the user expects), should this entity be returned in the label times?

**Comment by wang19k** [comment]
Yes I think the entity should be returned in the label times. At least for my applications, I would rather have the entity returned with as many labels as it can find, even if it isn't the specified amount.

**Comment by jeff-hernandez** [comment]
I agree and perhaps this can also be parameter. I think the search should return up to the specified amount of labels for each entity.

In [the uses cases](https://github.com/FeatureLabs/compose/issues/90#issuecomment-564264376) described previously, it seems like the data should return all the labels it finds. Not sure how this is different from the current behavior when setting `num_examples_per_instance` to -1.

**Comment by wang19k** [comment]
About the use cases, I realized that num_examples_per_instance does already cover this. I think the behavior should  just returning the specified # of labels per label or the best attempt. Basically, edited from above, given `num_examples_per_instance = {'A': 2, 'B':3, 'C': 3}`

- If the data had labels with exactly 2 'A's, 3 'B's, and 3 'C's, then this would be returned.
- If the data has 5 'A', 3 'B's, and 3 'C's, then 2 'A's, 3 'B's, and 3 'C's would be returned.
- If the data had 1 'A', 3 'B's, and 3 'C's, then all of the labels would be returned.

**Comment by jeff-hernandez** [comment]
This is a great idea. Thank you for explaining and sharing your feedback. I will keep you updated on the progress.

**Comment by jeff-hernandez** [comment]
@wang19k I linked the PR which can search based on the number of examples per label.

**Comment by jeff-hernandez** [comment]
Hi @wang19k,

This feature has been merged to master and should be available in the next release! If you would like to start using the feature, you can also install Compose from the master branch by running this command.

```
pip install git+https://github.com/FeatureLabs/compose.git
```

Let me know if you have any questions or additional feedback. Thanks again for the feature request!
